apiVersion: apps/v1
kind: Deployment
metadata:
  name: fogverse-master-merger-deployment
spec:
  selector:
    matchLabels:
      app: fogverse-master-merger-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: fogverse-master-merger-deployment
        master-merger: "true"
    spec:
      containers:
      - name: fogverse-master-merger-container
        image: ariqbasyar/fogverse:master-inference-merger
        imagePullPolicy: Always
        env:
        - name: CONSUMER_SERVERS
          value: "$LOCAL"
        - name: PRODUCER_SERVERS
          value: "$LOCAL"
      nodeSelector:
        kubernetes.io/hostname: debian-master
