version: '3'

services:
  input-pod:
    image: ariqbasyar/fogverse:input-1
    volumes:
      - ./logs/:/app/logs/
    environment:
    - CLOUD_KAFKA=${CLOUD_KAFKA}
    - LOCAL_KAFKA=${LOCAL_KAFKA}
    - SCENARIO=4
    - CAM_ID=1
    restart: always
    devices:
    - /dev/video0:/dev/video0
