version: '3'

services:
  preprocess-pod:
    image: ariqbasyar/fogverse:preprocess-raspberrypi
    volumes:
      - ./logs/:/app/logs/
    environment:
    - CONSUMER_SERVERS=${LOCAL_KAFKA}
    - PRODUCER_SERVERS=kafka-server
    restart: always
    extra_hosts:
    - kafka-server:${CLOUD_KAFKA}
