apiVersion: apps/v1
kind: Deployment
metadata:
  name: fogverse-preprocess-deployment
spec:
  selector:
    matchLabels:
      app: fogverse-preprocess-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: fogverse-preprocess-deployment
        preprocess: "true"
    spec:
      containers:
      - name: fogverse-preprocess-container
        image: ariqbasyar/final-project:preprocess-raspberrypi
        imagePullPolicy: Always
        env:
        - name: CONSUMER_SERVERS
          value: "192.168.1.190:9092,192.168.1.191:9092,192.168.1.192:9092"
        - name: PRODUCER_SERVERS
          value: "CLOUD"
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
