apiVersion: apps/v1
kind: Deployment
metadata:
  name: fogverse-preprocess-deployment
spec:
  selector:
    matchLabels:
      app: fogverse-preprocess-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: fogverse-preprocess-deployment
        preprocess: "true"
    spec:
      containers:
      - name: fogverse-preprocess-container
        image: ariqbasyar/fogverse:preprocess-raspberrypi
        imagePullPolicy: Always
        env:
        - name: CONSUMER_SERVERS
          value: "$LOCAL"
        - name: PRODUCER_SERVERS
          value: "$CLOUD"
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
